# Generated by Django 3.2.4 on 2021-06-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting_location',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='servicer',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-name']},
        ),
    ]
