# Generated by Django 3.2.4 on 2021-07-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0004_mreq_gui_mreq_use'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mreq_gui',
            new_name='Req_gui',
        ),
        migrations.RenameModel(
            old_name='mreq_use',
            new_name='Req_use',
        ),
        migrations.DeleteModel(
            name='Servicer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
