# Generated by Django 3.2.4 on 2021-07-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0006_guide_info_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide_info',
            old_name='dis_identify_num',
            new_name='identify_num',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='identify_num',
            new_name='dis_identify_num',
        ),
        migrations.AddField(
            model_name='guide_info',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
