# Generated by Django 3.2.4 on 2021-07-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0007_auto_20210714_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide_info',
            name='identify_num',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='dis_identify_num',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
