# Generated by Django 3.2.4 on 2021-07-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0008_auto_20210714_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='req_gui',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='req_use',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
